# -*- coding: utf-8 -*-
"""cse422lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I57kA9BpQ5dEbMwCgtj-9Mm7jYemdz43
"""

import random

def ab_prunn(n, d, a, b, maxx_player):
    if d == 0 or n.is_term():
        return n.eva_luate()

    if maxx_player:
        va_lue = float('-inf')
        for childrenn in n.g_child():
            va_lue = max(va_lue, ab_prunn(childrenn, d-1, a, b, False))
            a = max(a, va_lue)
            if b <= a:
                break
        return va_lue
    else:
        va_lue = float('inf')
        for childrenn in n.g_child():
            va_lue = min(va_lue, ab_prunn(childrenn, d-1, a, b, True))
            b = min(b, va_lue)
            if b <= a:
                break
        return va_lue

class Node:
    def __init__(self, name):
        self.name = name
        self.childrenn = []

    def is_term(self):
        return not self.childrenn

    def eva_luate(self):
        return random.choice([-1, 1])

    def g_child(self):
        return []


def simulate__game(inp):
    root = Node("Root")
    rplayed = 0
    curr_player = inp
    r_r = []
    count = 0

    while rplayed < 3:
        r = ab_prunn(root, 5, float('-inf'), float('inf'), curr_player == 1)
        if r == 1:
            winner = "Sub-Zero"
            count += 1
        else:
            winner = "Scorpion"

        r_r.append(f"Winner of Round {rplayed + 1}: {winner}")
        curr_player = 1 if curr_player == 0 else 0
        rplayed += 1

    if(count>1):
        game_winner="Sub-Zero"
    else:
        game_winner="Scorpion"
    print(f"Game Winner: {game_winner}")
    print(f"Total Rounds Played: {rplayed}")

    for round_r in r_r:
        print(round_r)
arr=[]
input_file=open("/content/22301178_MdTaosif_CSE422_02_Assignment03_task1_Summer2024_InputFile.txt","r")
for i in input_file:
    temp= i.split(" ")
    for j in temp:
        arr.append(int(j))
for i in arr:
    simulate__game(i)

